version: "3.8"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET=12345
      - PYTHONUNBUFFERED=TRUE
      - PYTHONDEBUGGER=True
    ports:
      - 80:8000
      - 3000:3000
    volumes:
      - .:/app
    restart: always
    logging:
      options:
        max-size: "200k"
        max-file: "2"
